image: busybox:latest

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r * public || true
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH